{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "sb-app.fullname" . }}
  labels:
    {{- include "sb-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
data: 
  conf: |
    {{- .Values.config | toYaml | nindent 4 }}
{{- end }}
